// Generated by CoffeeScript 1.6.3
module.exports = function(grunt) {
  var c, taskName;
  c = console;
  taskName = void 0;
  c.log(" // ----------------- 読み込みパッケージ名");
  for (taskName in grunt.file.readJSON('package.json').devDependencies) {
    if (taskName !== "grunt") {
      c.log(taskName);
      grunt.loadNpmTasks(taskName);
    }
  }
  c.log("");
  grunt.initConfig({
    sass: {
      dist: {
        files: [
          {
            expand: true,
            cwd: "scss",
            src: ["*.scss"],
            dest: "css/",
            ext: ".css"
          }
        ],
        options: {
          lineNumbers: true,
          style: 'expanded'
        }
      }
    },
    watch: {
      scss: {
        files: ["scss/*.scss"],
        tasks: ["_sass"]
      }
    }
  });
  grunt.registerTask("default", ["sass"]);
  return grunt.registerTask("_sass", ["sass"]);
};
