// Generated by CoffeeScript 1.6.3
module.exports = function(grunt) {
  var c, taskName;
  c = console;
  taskName = void 0;
  c.log(" // ----------------- 読み込みパッケージ名");
  for (taskName in grunt.file.readJSON('package.json').devDependencies) {
    if (taskName !== "grunt") {
      c.log(taskName);
      grunt.loadNpmTasks(taskName);
    }
  }
  c.log("");
  grunt.initConfig({
    'dart-sass': {
      target: {
        options: {
          expand: true,
        },
        files: {
          'css/top.css': 'scss/top.scss'
        }
      },
    },
    watch: {
      scss: {
        files: ["scss/*.scss"],
        tasks: ["_sass"]
      }
    }
  });
  grunt.loadNpmTasks('grunt-dart-sass')
  grunt.registerTask("default", ["dart-sass"]);
  return grunt.registerTask("_sass", ["dart-sass"]);
};
